CREATE DATABASE CRUD
GO
USE CRUD 
GO
CREATE TABLE FUNCIONARIO (
ID INT IDENTITY,
NOME VARCHAR(50),
CPF VARCHAR(11),
RG VARCHAR(9),
ORGAO_EMISSOR_RG VARCHAR(5),
TITULO_ELEITOR VARCHAR (12),
CNH VARCHAR(11),
GESTOR INT
);
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);
GO


CREATE TABLE ENDERECO(
ID  INT IDENTITY,
ID_FUNCIONARIO INT NOT NULL,
CEP VARCHAR(8),
ENDERECO VARCHAR(50),
NUMERO varchar(10),
COMPLEMENTO VARCHAR (30),
BAIRRO VARCHAR (20),
CIDADE VARCHAR (20),
ESTADO CHAR (2),
PONTO_REFERENCIA VARCHAR(50),
ATIVO INT

);
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (ID);
GO



ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_FUNCIONARIO
FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIO (ID);
GO



